[package]
name = "caller_modpath_aggregator"
version = "0.1.0"

[lib]

[dependencies]
caller_modpath_aggregator_functions = { path="./caller_modpath_aggregator_functions" }
caller_modpath_aggregator_macros = { path="./caller_modpath_aggregator_macros" }